export const walletCurrencyOptions = [
    { code: 'EUR', label: 'EUR - Euro' },
    { code: 'USD', label: 'USD - US Dollar' },
    { code: 'GBP', label: 'GBP - British Pound' },
    { code: 'JPY', label: 'JPY - Japanese Yen' },
    { code: 'CHF', label: 'CHF - Swiss Franc' },
    { code: 'CAD', label: 'CAD - Canadian Dollar' },
    { code: 'AUD', label: 'AUD - Australian Dollar' },
    { code: 'NZD', label: 'NZD - New Zealand Dollar' },
    { code: 'SEK', label: 'SEK - Swedish Krona' },
    { code: 'NOK', label: 'NOK - Norwegian Krone' },
    { code: 'DKK', label: 'DKK - Danish Krone' },
    { code: 'PLN', label: 'PLN - Polish Zloty' },
    { code: 'CZK', label: 'CZK - Czech Koruna' },
    { code: 'HUF', label: 'HUF - Hungarian Forint' },
    { code: 'RON', label: 'RON - Romanian Leu' },
    { code: 'BGN', label: 'BGN - Bulgarian Lev' },
    { code: 'TRY', label: 'TRY - Turkish Lira' },
    { code: 'CNY', label: 'CNY - Chinese Yuan' },
    { code: 'HKD', label: 'HKD - Hong Kong Dollar' },
    { code: 'SGD', label: 'SGD - Singapore Dollar' },
    { code: 'INR', label: 'INR - Indian Rupee' },
    { code: 'AED', label: 'AED - UAE Dirham' },
    { code: 'SAR', label: 'SAR - Saudi Riyal' },
    { code: 'ZAR', label: 'ZAR - South African Rand' },
    { code: 'BRL', label: 'BRL - Brazilian Real' },
    { code: 'MXN', label: 'MXN - Mexican Peso' },
] as const;
